literature={
    'Atwood'  : ['The answers you get from literature depends on the questions you pose .',
               'A word after a word after a word is power.',
               'War is what happens when language fails.',
               "You're never going to kill storytelling, because it's built into the human plan. we come with it."],
    'Pound'  : ['Great literature is simply language charged with meaning to the utmost possible degree.',
                 "If a nation's literature declines , the nation atrophies and decays",
                 "No man understands a deep book until he has seen and lived atleast part of it's contents.",
                 "Colloquial poetry is tothe wax real art as the barbar's wax dummy is to the sculpture."],
    'Updike'  : ['Writers may be disreputable, in corrigible, early to decay or late to bloom but they dare to go it alone',
                 'Books externalise our brains and turn our homes into thinking bodies',
                 'The study of literature threatens to become a kind of paleontology of failure and critisism a supercilious psychoanalysis of authors.',
                 'For some of us books are intrinsic to our sense of personal identity.'],
    'Calvino' : ['one writes fables in periods of oppression.',
                 'A classic is a book that has never finished saying what it has to say.',
                 'Reading is a possession a march toward  a possession',
                 'A writer is someone who tears himself to pieces in order to liberate his neighbor.'],
    'Forster' : ['Reverence is fatal to literature.',
                 'The only books that influence us are those for which we are ready , and which have gone a little farther down our particular path than we have yet got ourselves.',
                 'What is wonderful about great literature is that it transforms the man who reads it towards the condition of the man who wrote',
                 'Only a writer who has a sense of evilness can make goodness readable.']}
